name: Lint Heimdall

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
     - uses: actions/checkout@v3

     - name: Cache node modules
       uses: actions/cache@v3
       env:
         cache-name: cache-node-modules
       with:
         # npm cache files are stored in `~/.npm` on Linux/macOS
         path: ~/.npm
         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
         restore-keys: |
           ${{ runner.os }}-build-${{ env.cache-name }}-
           ${{ runner.os }}-build-
           ${{ runner.os }}-

     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
        node-version: '16.x'

     - name: Install project dependencies
       run: yarn install --frozen-lockfile --production

     - name: Run lint
       run: yarn run lint:ci
